
------------------------------------------------------------------------------------------------------------------------------
-- THIS SCRIPT FILE WILL DROP ALL TABLES FOR THE ACTIVITY FUND DATABASE; 
-- NOTE:  THE TABLE ORDER IS REQUIRED DUE TO FOREIGN KEY CONSTRAINTS;
-- LAST UPDATED 2009.03.20 BY FRED;
------------------------------------------------------------------------------------------------------------------------------

USE EDSACT001050
DROP TABLE CURRENT_VALUES
DROP TABLE DIMR1
DROP TABLE DIMR2
DROP TABLE DIMR3
DROP TABLE DIMR4
DROP TABLE DIMR5
DROP TABLE DIMR6
DROP TABLE DIMX1
DROP TABLE DIMX2
DROP TABLE DIMX3
DROP TABLE DIMX4
DROP TABLE DIMX5
DROP TABLE DIMX6
DROP TABLE DIMX7
DROP TABLE DIMX8
DROP TABLE DIMX9
DROP TABLE OUTSTANDINGRECEIPTS
DROP TABLE OUTSTANDINGCHECKS
DROP TABLE VEND_INFO
DROP TABLE VEND_AUDIT
DROP TABLE INVOICES
DROP TABLE RECEIPT_DETL
DROP TABLE RECEIPT_INFO
DROP TABLE RECEIPT_HISTORY
DROP TABLE RECEIPT_BATCH
DROP TABLE SCHOOL_INFO
DROP TABLE SHIPPING
DROP TABLE SIGNATURES
DROP TABLE SYSTEM_BACKUPS
DROP TABLE SYSTEM_FTP
DROP TABLE SYSTEM_INFO
DROP TABLE SYSTEM_UPDATES
DROP TABLE TRANSACTIONS
DROP TABLE TRANSFERS
DROP TABLE CHKS_DETL
DROP TABLE CHKS_INFO
DROP TABLE CHKS_REG
DROP TABLE CHKS_AUDIT
DROP TABLE VOIDCHECK
DROP TABLE VOIDRECEIPT
DROP TABLE DEPOSIT_INFO
DROP TABLE LOGOS
DROP TABLE REQ_APPROVER
DROP TABLE REQ_AUDIT
DROP TABLE REQ_QUEUE
DROP TABLE REQ_COMMENTS
DROP TABLE REQ_DETL
DROP TABLE REQ_INFO
DROP TABLE UPERMISSIONS
DROP TABLE UPERMISSIONS_AUXILIARY
DROP TABLE UASSEMBLIES
DROP TABLE UASSEMBLIES_AUXILIARY
DROP TABLE USER_INFO
DROP TABLE USER_ACCOUNTS
DROP TABLE PURC_DETL
DROP TABLE PURC_INFO
DROP TABLE PURC_HISTORY
DROP TABLE OCAS_EXP
DROP TABLE OCAS_REV
DROP TABLE ACCT_SUB
DROP TABLE ACCT_INFO
DROP TABLE ACCT_HISTORY
DROP TABLE ACCT_AUDIT
DROP TABLE BANK_INFO
DROP TABLE BANK_HISTORY
